"""Type definitions for Claude SDK.

This package re-exports all types for backwards compatibility.
Types are organized into submodules:
- base: Type aliases, literals, and thinking configuration
- agents: Agent definitions and presets
- permissions: Permission system types
- hooks: Hook system types (inputs, outputs, matchers, callbacks)
- mcp: MCP server and plugin configuration
- sandbox: Sandbox configuration
- messages: Content blocks, message types, and stream events
- options: ClaudeAgentOptions
- control: SDK control protocol types
"""

from __future__ import annotations

from .agents import AgentDefinition, SystemPromptPreset, ToolsPreset
from .base import (
    ApiKeySource,
    PermissionMode,
    ReasoningEffort,
    SdkBeta,
    SettingSource,
    StopReason,
    ThinkingConfig,
    ThinkingConfigAdaptive,
    ThinkingConfigDisabled,
    ThinkingConfigEnabled,
)
from .control import (
    ControlErrorResponse,
    ControlRequestUnion,
    ControlResponse,
    SDKControlInitializeRequest,
    SDKControlInterruptRequest,
    SDKControlMcpMessageRequest,
    SDKControlPermissionRequest,
    SDKControlRequest,
    SDKControlResponse,
    SDKControlRewindFilesRequest,
    SDKControlSetPermissionModeRequest,
    SDKControlStopTaskRequest,
    SDKHookCallbackRequest,
    parse_control_request,
)
from .hooks import (
    AsyncHookJSONOutput,
    BaseHookInput,
    HookCallback,
    HookContext,
    HookEvent,
    HookInput,
    HookJSONOutput,
    HookMatcher,
    HookSpecificOutput,
    NotificationHookInput,
    NotificationHookSpecificOutput,
    PermissionRequestHookInput,
    PermissionRequestHookSpecificOutput,
    PostToolUseFailureHookInput,
    PostToolUseFailureHookSpecificOutput,
    PostToolUseHookInput,
    PostToolUseHookSpecificOutput,
    PreCompactHookInput,
    PreToolUseHookInput,
    PreToolUseHookSpecificOutput,
    SessionStartHookSpecificOutput,
    StopHookInput,
    SubagentStartHookInput,
    SubagentStartHookSpecificOutput,
    SubagentStopHookInput,
    SyncHookJSONOutput,
    UserPromptSubmitHookInput,
    UserPromptSubmitHookSpecificOutput,
)
from .input_types import (
    TOOL_INPUT_TYPES,
    AgentInput,
    AskUserQuestion,
    AskUserQuestionInput,
    AskUserQuestionOption,
    BashInput,
    BashOutputInput,
    ExitPlanModeInput,
    FileEditInput,
    FileReadInput,
    FileWriteInput,
    GlobInput,
    GrepInput,
    KillShellInput,
    ListMcpResourcesInput,
    NotebookEditInput,
    ReadMcpResourceInput,
    TodoItem,
    TodoWriteInput,
    ToolInput,
    WebFetchInput,
    WebSearchInput,
)
from .mcp import (
    McpHttpServerConfig,
    McpSdkServerConfig,
    McpServerConfig,
    McpSSEServerConfig,
    McpStdioServerConfig,
    SdkPluginConfig,
)
from .output_types import (
    TOOL_OUTPUT_TYPES,
    AskUserQuestionOutput,
    BashOutput,
    BashOutputToolOutput,
    EditOutput,
    ExitPlanModeOutput,
    GlobOutput,
    GrepContentOutput,
    GrepCountEntry,
    GrepCountOutput,
    GrepFilesOutput,
    GrepMatch,
    GrepOutput,
    ImageFileOutput,
    KillBashOutput,
    ListMcpResourcesOutput,
    McpResourceContent,
    McpResourceInfo,
    NotebookCell,
    NotebookEditOutput,
    NotebookFileOutput,
    PDFFileOutput,
    PDFPage,
    PDFPageImage,
    ReadMcpResourceOutput,
    ReadOutput,
    TaskOutput,
    TaskOutputUsage,
    TextFileOutput,
    TodoWriteOutput,
    TodoWriteStats,
    ToolOutput,
    WebFetchOutput,
    WebSearchOutput,
    WebSearchResult,
    WriteOutput,
)
from .tool_use_results import (
    BashToolUseResult,
    EditToolUseResult,
    ReadFileInfo,
    ReadToolUseResult,
    StructuredPatchHunk,
    TodoUseResultItem,
    TodoWriteToolUseResult,
    ToolUseResult,
    WriteToolUseResult,
)
from .content_blocks import (
    ContentBlock,
    TextBlock,
    ThinkingBlock,
    ToolResultBlock,
    ToolUseBlock,
    parse_content_block,
)

from .messages import (
    AssistantMessage,
    AssistantMessageError,
    CompactBoundarySystemMessage,
    HookResponseSystemMessage,
    HookStartedSystemMessage,
    McpServerStatus,
    Message,
    ModelUsage,
    ResultMessage,
    SDKPermissionDenial,
    StatusSystemMessage,
    StreamEvent,
    SystemMessage,
    TaskNotificationSystemMessage,
    TaskStartedSystemMessage,
    ToolProgressMessage,
    ToolUseSummaryMessage,
    TriggerMetadata,
    Usage,
    UserMessage,
    UserPromptMessage,
    UserPromptMessageContent,
    parse_system_message,
)
from .options import ClaudeAgentOptions
from .permissions import (
    CanUseTool,
    PermissionBehavior,
    PermissionResult,
    PermissionResultAllow,
    PermissionResultDeny,
    PermissionRuleValue,
    PermissionUpdate,
    PermissionUpdateDestination,
    ToolPermissionContext,
)
from .sandbox import SandboxIgnoreViolations, SandboxNetworkConfig, SandboxSettings

__all__ = [
    # base
    "ApiKeySource",
    "PermissionMode",
    "ReasoningEffort",
    "SdkBeta",
    "SettingSource",
    "StopReason",
    "ThinkingConfig",
    "ThinkingConfigAdaptive",
    "ThinkingConfigDisabled",
    "ThinkingConfigEnabled",
    # agents
    "AgentDefinition",
    "SystemPromptPreset",
    "ToolsPreset",
    # permissions
    "CanUseTool",
    "PermissionBehavior",
    "PermissionResult",
    "PermissionResultAllow",
    "PermissionResultDeny",
    "PermissionRuleValue",
    "PermissionUpdate",
    "PermissionUpdateDestination",
    "ToolPermissionContext",
    # hooks
    "AsyncHookJSONOutput",
    "BaseHookInput",
    "HookCallback",
    "HookContext",
    "HookEvent",
    "HookInput",
    "HookJSONOutput",
    "HookMatcher",
    "HookSpecificOutput",
    "NotificationHookInput",
    "NotificationHookSpecificOutput",
    "PermissionRequestHookInput",
    "PermissionRequestHookSpecificOutput",
    "PostToolUseFailureHookInput",
    "PostToolUseFailureHookSpecificOutput",
    "PostToolUseHookInput",
    "PostToolUseHookSpecificOutput",
    "PreCompactHookInput",
    "PreToolUseHookInput",
    "PreToolUseHookSpecificOutput",
    "SessionStartHookSpecificOutput",
    "StopHookInput",
    "SubagentStartHookInput",
    "SubagentStartHookSpecificOutput",
    "SubagentStopHookInput",
    "SyncHookJSONOutput",
    "UserPromptSubmitHookInput",
    "UserPromptSubmitHookSpecificOutput",
    # mcp
    "McpHttpServerConfig",
    "McpSdkServerConfig",
    "McpServerConfig",
    "McpSSEServerConfig",
    "McpStdioServerConfig",
    "SdkPluginConfig",
    # sandbox
    "SandboxIgnoreViolations",
    "SandboxNetworkConfig",
    "SandboxSettings",
    # messages
    "AssistantMessage",
    "AssistantMessageError",
    "CompactBoundarySystemMessage",
    "ContentBlock",
    "HookResponseSystemMessage",
    "HookStartedSystemMessage",
    "McpServerStatus",
    "Message",
    "ModelUsage",
    "ResultMessage",
    "SDKPermissionDenial",
    "StatusSystemMessage",
    "StreamEvent",
    "SystemMessage",
    "TaskNotificationSystemMessage",
    "TaskStartedSystemMessage",
    "TextBlock",
    "ThinkingBlock",
    "ToolProgressMessage",
    "ToolResultBlock",
    "ToolUseBlock",
    "ToolUseSummaryMessage",
    "TriggerMetadata",
    "Usage",
    "UserMessage",
    "UserPromptMessage",
    "UserPromptMessageContent",
    "parse_content_block",
    "parse_system_message",
    # options
    "ClaudeAgentOptions",
    # control
    "ControlErrorResponse",
    "ControlRequestUnion",
    "ControlResponse",
    "SDKControlInitializeRequest",
    "SDKControlInterruptRequest",
    "SDKControlMcpMessageRequest",
    "SDKControlPermissionRequest",
    "SDKControlRequest",
    "SDKControlResponse",
    "SDKControlRewindFilesRequest",
    "SDKControlSetPermissionModeRequest",
    "SDKControlStopTaskRequest",
    "SDKHookCallbackRequest",
    "parse_control_request",
    "ToolInput",
    "TOOL_INPUT_TYPES",
    "AgentInput",
    "AskUserQuestion",
    "AskUserQuestionInput",
    "AskUserQuestionOption",
    "BashInput",
    "BashOutputInput",
    "FileEditInput",
    "FileReadInput",
    "FileWriteInput",
    "GlobInput",
    "GrepInput",
    "KillShellInput",
    "NotebookEditInput",
    "WebFetchInput",
    "WebSearchInput",
    "TodoItem",
    "TodoWriteInput",
    "ExitPlanModeInput",
    "ListMcpResourcesInput",
    "ReadMcpResourceInput",
    # output_types
    "TOOL_OUTPUT_TYPES",
    "AskUserQuestionOutput",
    "BashOutput",
    "BashOutputToolOutput",
    "EditOutput",
    "ExitPlanModeOutput",
    "GlobOutput",
    "GrepContentOutput",
    "GrepCountEntry",
    "GrepCountOutput",
    "GrepFilesOutput",
    "GrepMatch",
    "GrepOutput",
    "ImageFileOutput",
    "KillBashOutput",
    "ListMcpResourcesOutput",
    "McpResourceContent",
    "McpResourceInfo",
    "NotebookCell",
    "NotebookEditOutput",
    "NotebookFileOutput",
    "PDFFileOutput",
    "PDFPage",
    "PDFPageImage",
    "ReadMcpResourceOutput",
    "ReadOutput",
    "TaskOutput",
    "TaskOutputUsage",
    "TextFileOutput",
    "TodoWriteOutput",
    "TodoWriteStats",
    "ToolOutput",
    "WebFetchOutput",
    "WebSearchOutput",
    "WebSearchResult",
    "WriteOutput",
    # tool_use_results
    "BashToolUseResult",
    "EditToolUseResult",
    "ReadFileInfo",
    "ReadToolUseResult",
    "StructuredPatchHunk",
    "TodoUseResultItem",
    "TodoWriteToolUseResult",
    "ToolUseResult",
    "WriteToolUseResult",
]
