"""Type definitions for Claude SDK."""

from __future__ import annotations
from collections.abc import Callable

from mcp.types import ElicitResult

from .agents import AgentDefinition, AgentInfo, AgentWireDefinition, ToolsPreset
from .base import (
    ApiKeySource,
    AssistantMessageError,
    ElicitationAction,
    ElicitationMode,
    HookPermissionDecision,
    PermissionDecisionClassification,
    PermissionMode,
    PermissionBehavior,
    ReasoningEffort,
    SdkBeta,
    SettingSource,
    StopReason,
    FastModeState,
    ToolName,
)
from .thinking import (
    ThinkingConfig,
    ThinkingConfigAdaptive,
    ThinkingConfigDisabled,
    ThinkingConfigEnabled,
)
from .context_usage import (
    ContextUsageAgent,
    ContextUsageAttachmentBreakdown,
    ContextUsageCategory,
    ContextUsageDeferredBuiltinTool,
    ContextUsageGridCell,
    ContextUsageMcpTool,
    ContextUsageMemoryFile,
    ContextUsageMessageBreakdown,
    ContextUsageSkillFrontmatter,
    ContextUsageSkills,
    ContextUsageSlashCommands,
    ContextUsageSystemPromptSection,
    ContextUsageSystemTool,
    ContextUsageToolCallBreakdown,
    SDKControlGetContextUsageResponse,
)
from .control import (
    ControlErrorResponse,
    ControlRequestUnion,
    IncomingControlRequest,
    OutgoingControlRequest,
    ControlResponse,
    SDKControlApplyFlagSettingsRequest,
    SDKControlMcpAuthenticateRequest,
    SDKControlMcpClearAuthRequest,
    SDKControlMcpReconnectRequest,
    SDKControlMcpSetServersRequest,
    SDKControlMcpStatusRequest,
    SDKControlMcpToggleRequest,
    SDKControlSetMaxThinkingTokensRequest,
    SDKControlSetModelRequest,
    SDKControlCancelAsyncMessageRequest,
    SDKControlChannelEnableRequest,
    ClaudeOAuthWaitForCompletionResponse,
    SDKControlClaudeOAuthWaitForCompletionRequest,
    SDKControlElicitationRequest,
    SDKControlEndSessionRequest,
    SDKControlInitializeRequest,
    SDKControlInterruptRequest,
    SDKControlMcpMessageRequest,
    SDKControlMcpOAuthCallbackUrlRequest,
    SDKControlPermissionRequest,
    AppliedSettings,
    GetSettingsResponse,
    McpAuthenticateResponse,
    RemoteControlResponse,
    SDKControlRemoteControlRequest,
    SettingsSource,
    SDKControlRequest,
    SDKControlResponse,
    SDKControlRewindFilesRequest,
    SDKControlSeedReadStateRequest,
    SDKControlSetPermissionModeRequest,
    SDKControlSetProactiveRequest,
    SDKControlSideQuestionRequest,
    SideQuestionResponse,
    SDKControlGetContextUsageRequest,
    SDKControlGetSettingsRequest,
    SDKControlStopTaskRequest,
    SDKHookCallbackRequest,
    incoming_control_request_adapter,
)
from .hooks import (
    AgentHookHandler,
    AgentHooksConfig,
    AsyncHookJSONOutput,
    BaseHookInput,
    CommandHookHandler,
    CwdChangedHookInput,
    CwdChangedHookSpecificOutput,
    PermissionDeniedHookInput,
    PermissionDeniedHookSpecificOutput,
    ElicitationHookInput,
    ElicitationHookSpecificOutput,
    ElicitationResultHookInput,
    ElicitationResultHookSpecificOutput,
    FileChangedHookInput,
    FileChangedHookSpecificOutput,
    HookCallback,
    HookContext,
    HookEvent,
    HookHandler,
    HookInput,
    HookJSONOutput,
    HookMatcher,
    HookMatcherConfig,
    HookSpecificOutput,
    PromptHookHandler,
    NotificationHookInput,
    NotificationHookSpecificOutput,
    PermissionRequestHookInput,
    SessionEndHookInput,
    SessionStartHookInput,
    SetupHookInput,
    PermissionRequestHookSpecificOutput,
    PostCompactHookInput,
    PostToolUseFailureHookInput,
    PostToolUseFailureHookSpecificOutput,
    PostToolUseHookInput,
    PostToolUseHookSpecificOutput,
    PreCompactHookInput,
    PreToolUseHookInput,
    PreToolUseHookSpecificOutput,
    SessionStartHookSpecificOutput,
    StopHookInput,
    SubagentStartHookInput,
    TaskCompletedHookInput,
    TaskCreatedHookInput,
    TeammateIdleHookInput,
    SubagentStartHookSpecificOutput,
    SubagentStopHookInput,
    SyncHookJSONOutput,
    UserPromptSubmitHookInput,
    UserPromptSubmitHookSpecificOutput,
    WorktreeCreateHookInput,
    WorktreeCreateHookSpecificOutput,
    WorktreeRemoveHookInput,
    InstructionsLoadedHookInput,
)
from .input_types import (
    TOOL_INPUT_TYPES,
    AgentInput,
    AskUserQuestion,
    AskUserQuestionInput,
    AskUserQuestionOption,
    BashInput,
    BashOutputInput,
    EnterPlanModeInput,
    ExitPlanModeInput,
    ExitWorktreeInput,
    FileEditInput,
    FileReadInput,
    FileWriteInput,
    GlobInput,
    GrepInput,
    KillShellInput,
    ListMcpResourcesInput,
    NotebookEditInput,
    ReadMcpResourceInput,
    SkillInput,
    TodoItem,
    TodoWriteInput,
    ToolInput,
    WebFetchInput,
    WebSearchInput,
)
from .mcp import (
    JSONRPCError,
    JSONRPCErrorResponse,
    JSONRPCMessage,
    JSONRPCNotification,
    JSONRPCRequest,
    JSONRPCResponse,
    JSONRPCResultResponse,
    McpConnectionStatus,
    McpHttpServerConfig,
    McpClaudeAIProxyServerConfig,
    McpSdkServerConfig,
    McpSdkServerConfigWithInstance,
    McpServerConfig,
    McpServerConfigForProcessTransport,
    McpServerStatusConfig,
    McpServerStatusEntry,
    McpServerVersionInfo,
    McpSetServersResult,
    McpSSEServerConfig,
    McpStatusResponse,
    McpStdioServerConfig,
    McpToolStatus,
    RequestId,
    SdkPluginConfig,
    ExternalMcpServerConfig,
)
from .output_types import (
    TOOL_USE_RESULT_TYPES,
    SDKDeferredToolUse,
    AgentAsyncLaunchedOutput,
    AgentCacheCreation,
    AgentCompletedOutput,
    AgentOutput,
    AgentOutputTextContent,
    AgentOutputUsage,
    AgentServerToolUse,
    AskUserQuestionItem,
    AskUserQuestionOutput,
    BashOutput,
    BashOutputOutput,
    ConfigOutput,
    EditOutput,
    EnterPlanModeOutput,
    EnterWorktreeOutput,
    ExitWorktreeOutput,
    KillShellOutput,
    ExitPlanModeOutput,
    GitDiff,
    GlobOutput,
    GrepOutput,
    ListMcpResourcesOutput,
    McpOutput,
    McpResourceEntry,
    NotebookEditOutput,
    ReadFileInfo,
    ReadImageDimensions,
    ReadImageFileInfo,
    ReadImageOutput,
    ReadMcpResourceContentItem,
    ReadMcpResourceOutput,
    ReadNotebookFileInfo,
    ReadNotebookOutput,
    ReadOutput,
    ReadPartsFileInfo,
    ReadPartsOutput,
    ReadPdfFileInfo,
    ReadPdfOutput,
    ReadTextOutput,
    SkillOutput,
    StructuredPatchHunk,
    # SubscribeMcpResourceOutput,
    # SubscribePollingOutput,
    TaskInfo,
    TaskOutputResult,
    TaskStopOutput,
    TodoWriteOutput,
    ToolUseResult,
    # UnsubscribeMcpResourceOutput,
    # UnsubscribePollingOutput,
    WebFetchOutput,
    WebSearchHit,
    WebSearchOutput,
    WebSearchToolResult,
    WriteOutput,
)
from .content_blocks import (
    AssistantContentBlock,
    AssistantMessageContent,
    ContentBlock,
    ImageBlock,
    ImageSource,
    MessageParam,
    TextBlock,
    ThinkingBlock,
    ToolResultBlock,
    ToolUseBlock,
    UserContentBlock,
)
from .session import (
    SDKSessionInfo,
    SessionMessage,
)
from .usage import ModelUsage, Usage
from .messages import (
    AssistantMessage,
    BaseResultMessage,
    PromptSuggestionMessage,
    RateLimitInfo,
    RateLimitMessage,
    ResultErrorMessage,
    ResultMessage,
    ResultSuccessMessage,
    SDKPermissionDenial,
    StreamEvent,
    AuthStatusMessage,
    ToolProgressMessage,
    ToolUseSummaryMessage,
    MiscMessages,
    UserMessage,
)
from .prompts import (
    DocumentMediaType,
    ImageMediaType,
    UserDocumentPrompt,
    PlainTextMediaType,
    UserDocumentURLPrompt,
    UserFilePrompt,
    UserImagePrompt,
    UserImageURLPrompt,
    UserPlainTextDocumentPrompt,
    UserPrompt,
    UserTextPrompt,
)
from .prompt_requests import PromptRequest, PromptRequestOption, PromptResponse
from .options import (
    ClaudeAgentOptions,
    BaseSessionConfig,
    ContinueLatest,
    FromPR,
    NewSession,
    ResumeSession,
    SessionConfig,
    ToolConfig,
)
from .permissions import (
    CanUseTool,
    OnUserQuestion,
    PermissionResult,
    PermissionResultAllow,
    PermissionResultDeny,
    PermissionRuleValue,
    PermissionUpdate,
    PermissionUpdateDestination,
    ToolPermissionContext,
)
from .settings import (
    ClaudeCodeSettings,
    Filesystem,
    Hooks,
    Network,
    Permissions,
    Sandbox,
)
from .server_info import ClaudeCodeAgentInfo, ClaudeCodeServerInfo, ClaudeCodeCommandInfo
from .system_messages import (
    system_message_adapter,
    TriggerMetadata,
    TaskProgressUsage,
    StatusSystemMessage,
    BaseSystemMessage,
    CompactBoundarySystemMessage,
    HookResponseSystemMessage,
    McpServerStatus,
    SessionState,
    HookStartedSystemMessage,
    InitSystemMessage,
    FilesPersistedSystemMessage,
    APIRetrySystemMessage,
    HookProgressSystemMessage,
    SessionStateChangedMessage,
    TaskNotificationSystemMessage,
    TaskProgressSystemMessage,
    TaskStartedSystemMessage,
    SystemMessageUnion,
    LocalCommandOutputMessage,
    ElicitationCompleteMessage,
)

from typing import Annotated, Any
from collections.abc import Awaitable

from pydantic import Discriminator, Tag, TypeAdapter


def _message_discriminator(data: Any) -> str:
    """Route messages by ``type``, with ``subtype`` for result messages."""
    if isinstance(data, dict):
        msg_type: str = data.get("type", "")
        if msg_type == "result":
            return "result_success" if data.get("subtype") == "success" else "result_error"
        return msg_type
    return str(type(data).__name__)


MessageUnion = (
    UserMessage
    | AssistantMessage
    | ResultMessage
    | StreamEvent
    | RateLimitMessage
    | ToolProgressMessage
    | ToolUseSummaryMessage
    | AuthStatusMessage
    | PromptSuggestionMessage
    | SystemMessageUnion
)

Message = Annotated[
    Annotated[UserMessage, Tag("user")]
    | Annotated[AssistantMessage, Tag("assistant")]
    | Annotated[ResultSuccessMessage, Tag("result_success")]
    | Annotated[ResultErrorMessage, Tag("result_error")]
    | Annotated[StreamEvent, Tag("stream_event")]
    | Annotated[RateLimitMessage, Tag("rate_limit_event")]
    | Annotated[ToolProgressMessage, Tag("tool_progress")]
    | Annotated[ToolUseSummaryMessage, Tag("tool_use_summary")]
    | Annotated[AuthStatusMessage, Tag("auth_status")]
    | Annotated[PromptSuggestionMessage, Tag("prompt_suggestion")]
    | Annotated[SystemMessageUnion, Tag("system")],
    Discriminator(_message_discriminator),
]
"""Discriminated union of all wire-format message types."""

message_adapter: TypeAdapter[Message] = TypeAdapter(Message)

OnElicitation = Callable[[SDKControlElicitationRequest], Awaitable[ElicitResult]]
"""Callback for handling MCP elicitation requests.

Called when an MCP server requests user input and no hook handles it.
If not provided, elicitation requests will be declined automatically.
"""

__all__ = [
    "TOOL_INPUT_TYPES",
    "TOOL_USE_RESULT_TYPES",
    "APIRetrySystemMessage",
    "AgentAsyncLaunchedOutput",
    "AgentCacheCreation",
    "AgentCompletedOutput",
    "AgentDefinition",
    "AgentHookHandler",
    "AgentHooksConfig",
    "AgentInfo",
    "AgentInput",
    "AgentOutput",
    "AgentOutputTextContent",
    "AgentOutputUsage",
    "AgentServerToolUse",
    "AgentWireDefinition",
    "ApiKeySource",
    "AppliedSettings",
    "AskUserQuestion",
    "AskUserQuestionInput",
    "AskUserQuestionItem",
    "AskUserQuestionOption",
    "AskUserQuestionOutput",
    "AssistantContentBlock",
    "AssistantMessage",
    "AssistantMessageContent",
    "AssistantMessageError",
    "AsyncHookJSONOutput",
    "AuthStatusMessage",
    "BaseHookInput",
    "BaseResultMessage",
    "BaseSessionConfig",
    "BaseSystemMessage",
    "BashInput",
    "BashOutput",
    "BashOutputInput",
    "BashOutputOutput",
    "CanUseTool",
    "ClaudeAgentOptions",
    "ClaudeCodeAgentInfo",
    "ClaudeCodeCommandInfo",
    "ClaudeCodeServerInfo",
    "ClaudeCodeSettings",
    "ClaudeOAuthWaitForCompletionResponse",
    "CommandHookHandler",
    "CompactBoundarySystemMessage",
    "ConfigOutput",
    "ContentBlock",
    "ContextUsageAgent",
    "ContextUsageAttachmentBreakdown",
    "ContextUsageCategory",
    "ContextUsageDeferredBuiltinTool",
    "ContextUsageGridCell",
    "ContextUsageMcpTool",
    "ContextUsageMemoryFile",
    "ContextUsageMessageBreakdown",
    "ContextUsageSkillFrontmatter",
    "ContextUsageSkills",
    "ContextUsageSlashCommands",
    "ContextUsageSystemPromptSection",
    "ContextUsageSystemTool",
    "ContextUsageToolCallBreakdown",
    "ContinueLatest",
    "ControlErrorResponse",
    "ControlRequestUnion",
    "ControlResponse",
    "CwdChangedHookInput",
    "CwdChangedHookSpecificOutput",
    "DocumentMediaType",
    "EditOutput",
    "ElicitationAction",
    "ElicitationCompleteMessage",
    "ElicitationHookInput",
    "ElicitationHookSpecificOutput",
    "ElicitationMode",
    "ElicitationResultHookInput",
    "ElicitationResultHookSpecificOutput",
    "EnterPlanModeInput",
    "EnterPlanModeOutput",
    "EnterWorktreeOutput",
    "ExitPlanModeInput",
    "ExitPlanModeOutput",
    "ExitWorktreeInput",
    "ExitWorktreeOutput",
    "ExternalMcpServerConfig",
    "FastModeState",
    "FileChangedHookInput",
    "FileChangedHookSpecificOutput",
    "FileEditInput",
    "FileReadInput",
    "FileWriteInput",
    "FilesPersistedSystemMessage",
    "Filesystem",
    "FromPR",
    "GetSettingsResponse",
    "GitDiff",
    "GlobInput",
    "GlobOutput",
    "GrepInput",
    "GrepOutput",
    "HookCallback",
    "HookContext",
    "HookEvent",
    "HookHandler",
    "HookInput",
    "HookJSONOutput",
    "HookMatcher",
    "HookMatcherConfig",
    "HookPermissionDecision",
    "HookProgressSystemMessage",
    "HookResponseSystemMessage",
    "HookSpecificOutput",
    "HookStartedSystemMessage",
    "Hooks",
    "ImageBlock",
    "ImageMediaType",
    "ImageSource",
    "IncomingControlRequest",
    "InitSystemMessage",
    "InstructionsLoadedHookInput",
    "JSONRPCError",
    "JSONRPCErrorResponse",
    "JSONRPCMessage",
    "JSONRPCNotification",
    "JSONRPCRequest",
    "JSONRPCResponse",
    "JSONRPCResultResponse",
    "KillShellInput",
    "KillShellOutput",
    "ListMcpResourcesInput",
    "ListMcpResourcesOutput",
    "LocalCommandOutputMessage",
    "McpAuthenticateResponse",
    "McpClaudeAIProxyServerConfig",
    "McpConnectionStatus",
    "McpHttpServerConfig",
    "McpOutput",
    "McpResourceEntry",
    "McpSSEServerConfig",
    "McpSdkServerConfig",
    "McpSdkServerConfigWithInstance",
    "McpServerConfig",
    "McpServerConfigForProcessTransport",
    "McpServerStatus",
    "McpServerStatusConfig",
    "McpServerStatusEntry",
    "McpServerVersionInfo",
    "McpSetServersResult",
    "McpStatusResponse",
    "McpStdioServerConfig",
    "McpToolStatus",
    "Message",
    "MessageParam",
    "MiscMessages",
    "ModelUsage",
    "Network",
    "NewSession",
    "NotebookEditInput",
    "NotebookEditOutput",
    "NotificationHookInput",
    "NotificationHookSpecificOutput",
    "OnElicitation",
    "OnUserQuestion",
    "OutgoingControlRequest",
    "PermissionBehavior",
    "PermissionDecisionClassification",
    "PermissionDeniedHookInput",
    "PermissionDeniedHookSpecificOutput",
    "PermissionMode",
    "PermissionRequestHookInput",
    "PermissionRequestHookSpecificOutput",
    "PermissionResult",
    "PermissionResultAllow",
    "PermissionResultDeny",
    "PermissionRuleValue",
    "PermissionUpdate",
    "PermissionUpdateDestination",
    "Permissions",
    "PlainTextMediaType",
    "PostCompactHookInput",
    "PostToolUseFailureHookInput",
    "PostToolUseFailureHookSpecificOutput",
    "PostToolUseHookInput",
    "PostToolUseHookSpecificOutput",
    "PreCompactHookInput",
    "PreToolUseHookInput",
    "PreToolUseHookSpecificOutput",
    "PromptHookHandler",
    "PromptRequest",
    "PromptRequestOption",
    "PromptResponse",
    "PromptSuggestionMessage",
    "RateLimitInfo",
    "RateLimitMessage",
    "ReadFileInfo",
    "ReadImageDimensions",
    "ReadImageFileInfo",
    "ReadImageOutput",
    "ReadMcpResourceContentItem",
    "ReadMcpResourceInput",
    "ReadMcpResourceOutput",
    "ReadNotebookFileInfo",
    "ReadNotebookOutput",
    "ReadOutput",
    "ReadPartsFileInfo",
    "ReadPartsOutput",
    "ReadPdfFileInfo",
    "ReadPdfOutput",
    "ReadTextOutput",
    "ReasoningEffort",
    "RemoteControlResponse",
    "RequestId",
    "ResultErrorMessage",
    "ResultMessage",
    "ResultSuccessMessage",
    "ResumeSession",
    "SDKControlApplyFlagSettingsRequest",
    "SDKControlCancelAsyncMessageRequest",
    "SDKControlChannelEnableRequest",
    "SDKControlClaudeOAuthWaitForCompletionRequest",
    "SDKControlElicitationRequest",
    "SDKControlEndSessionRequest",
    "SDKControlGetContextUsageRequest",
    "SDKControlGetContextUsageResponse",
    "SDKControlGetSettingsRequest",
    "SDKControlInitializeRequest",
    "SDKControlInterruptRequest",
    "SDKControlMcpAuthenticateRequest",
    "SDKControlMcpClearAuthRequest",
    "SDKControlMcpMessageRequest",
    "SDKControlMcpOAuthCallbackUrlRequest",
    "SDKControlMcpReconnectRequest",
    "SDKControlMcpSetServersRequest",
    "SDKControlMcpStatusRequest",
    "SDKControlMcpToggleRequest",
    "SDKControlPermissionRequest",
    "SDKControlRemoteControlRequest",
    "SDKControlRequest",
    "SDKControlResponse",
    "SDKControlRewindFilesRequest",
    "SDKControlSeedReadStateRequest",
    "SDKControlSetMaxThinkingTokensRequest",
    "SDKControlSetModelRequest",
    "SDKControlSetPermissionModeRequest",
    "SDKControlSetProactiveRequest",
    "SDKControlSideQuestionRequest",
    "SDKControlStopTaskRequest",
    "SDKDeferredToolUse",
    "SDKHookCallbackRequest",
    "SDKPermissionDenial",
    "SDKSessionInfo",
    "Sandbox",
    "SdkBeta",
    "SdkPluginConfig",
    "SessionConfig",
    "SessionEndHookInput",
    "SessionMessage",
    "SessionStartHookInput",
    "SessionStartHookSpecificOutput",
    "SessionState",
    "SessionStateChangedMessage",
    "SettingSource",
    "SettingsSource",
    "SetupHookInput",
    "SideQuestionResponse",
    "SkillInput",
    "SkillOutput",
    "StatusSystemMessage",
    "StopHookInput",
    "StopReason",
    "StreamEvent",
    "StructuredPatchHunk",
    "SubagentStartHookInput",
    "SubagentStartHookSpecificOutput",
    "SubagentStopHookInput",
    # "SubscribeMcpResourceOutput",
    # "SubscribePollingOutput",
    "SyncHookJSONOutput",
    "SystemMessageUnion",
    "TaskCompletedHookInput",
    "TaskCreatedHookInput",
    "TaskInfo",
    "TaskNotificationSystemMessage",
    "TaskOutputResult",
    "TaskProgressSystemMessage",
    "TaskProgressUsage",
    "TaskStartedSystemMessage",
    "TaskStopOutput",
    "TeammateIdleHookInput",
    "TextBlock",
    "ThinkingBlock",
    "ThinkingConfig",
    "ThinkingConfigAdaptive",
    "ThinkingConfigDisabled",
    "ThinkingConfigEnabled",
    "TodoItem",
    "TodoWriteInput",
    "TodoWriteOutput",
    "ToolConfig",
    "ToolInput",
    "ToolName",
    "ToolPermissionContext",
    "ToolProgressMessage",
    "ToolResultBlock",
    "ToolUseBlock",
    "ToolUseResult",
    "ToolUseSummaryMessage",
    "ToolsPreset",
    "TriggerMetadata",
    # "UnsubscribeMcpResourceOutput",
    # "UnsubscribePollingOutput",
    "Usage",
    "UserContentBlock",
    "UserDocumentPrompt",
    "UserDocumentURLPrompt",
    "UserFilePrompt",
    "UserImagePrompt",
    "UserImageURLPrompt",
    "UserMessage",
    "UserPlainTextDocumentPrompt",
    "UserPrompt",
    "UserPromptSubmitHookInput",
    "UserPromptSubmitHookSpecificOutput",
    "UserTextPrompt",
    "WebFetchInput",
    "WebFetchOutput",
    "WebSearchHit",
    "WebSearchInput",
    "WebSearchOutput",
    "WebSearchToolResult",
    "WorktreeCreateHookInput",
    "WorktreeCreateHookSpecificOutput",
    "WorktreeRemoveHookInput",
    "WriteOutput",
    "incoming_control_request_adapter",
    "message_adapter",
    "system_message_adapter",
]
