# generated by datamodel-codegen:
#   filename:  claude-code-settings-titled.json
#   timestamp: 2026-02-27T15:17:03+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import AnyUrl, ConfigDict, Field, RootModel

from clawd_code_sdk.models.base import ClaudeCodeBaseModel


class Attribution(ClaudeCodeBaseModel):
    """
    Customize attribution for git commits and pull requests. See https://code.claude.com/docs/en/settings#attribution-settings
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    commit: str | None = None
    """
    Attribution for git commits, including any trailers. Empty string hides commit attribution
    """
    pr: str | None = None
    """
    Attribution for pull request descriptions. Empty string hides pull request attribution
    """


class AdditionalDirectory(RootModel[str]):
    root: str = Field(..., min_length=1)


class EnabledMcpjsonServer(AdditionalDirectory):
    pass


class DisabledMcpjsonServer(AdditionalDirectory):
    pass


class AllowedMcpServerByServerName(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server_name: str = Field(..., alias="serverName", pattern="^[a-zA-Z0-9_-]+$")
    """
    Name of the MCP server that users are allowed to configure
    """


class AllowedMcpServerByServerCommand(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server_command: list[str] = Field(..., alias="serverCommand")
    """
    Exact command and arguments used to start stdio servers
    """


class AllowedMcpServerByServerUrl(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server_url: str = Field(..., alias="serverUrl")
    """
    URL pattern for remote servers, supports wildcards (e.g., https://*.example.com/*)
    """


class DeniedMcpServerByServerName(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server_name: str = Field(..., alias="serverName", pattern="^[a-zA-Z0-9_-]+$")
    """
    Name of the MCP server that is explicitly blocked
    """


class DeniedMcpServerByServerCommand(AllowedMcpServerByServerCommand):
    pass


class DeniedMcpServerByServerUrl(AllowedMcpServerByServerUrl):
    pass


class StatusLine(ClaudeCodeBaseModel):
    """
    Custom status line display configuration. See https://code.claude.com/docs/en/statusline
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["command"] = "command"
    """
    The type of status line handler; must be set to "command" to run a custom shell script that receives JSON session data via stdin.
    """
    command: str
    """
    A shell command or path to a script that displays session information (context usage, costs, git status, etc.) by reading JSON data from stdin and writing output to stdout. See https://code.claude.com/docs/en/statusline
    """
    padding: float | None = None
    """
    Optional number of extra horizontal spacing characters added to the status line content; defaults to 0.
    """


class FileSuggestion(ClaudeCodeBaseModel):
    """
    Configure a custom script for @ file autocomplete. See https://code.claude.com/docs/en/settings#file-suggestion-settings
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["command"] = "command"
    """
    The type of file suggestion handler; must be set to "command" to execute a custom shell script that generates file suggestions for the @ file picker.
    """
    command: str
    """
    Shell command to execute for file suggestions
    """


class MarketplaceSourceUrl(ClaudeCodeBaseModel):
    """
    Where to fetch the marketplace from
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["url"] = "url"
    """
    Identifies the marketplace source type
    """
    url: AnyUrl
    """
    Direct URL to marketplace.json file
    """


class MarketplaceSourceHostPattern(ClaudeCodeBaseModel):
    """
    Where to fetch the marketplace from
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["hostPattern"] = "hostPattern"
    """
    Identifies the marketplace source type
    """
    host_pattern: str = Field(..., alias="hostPattern")
    """
    Git host pattern to trust for repositories in source specifications
    """


class MarketplaceSourceGithub(ClaudeCodeBaseModel):
    """
    Where to fetch the marketplace from
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["github"] = "github"
    """
    Identifies the marketplace source type
    """
    repo: str
    """
    GitHub repository in owner/repo format
    """
    ref: str | None = None
    """
    Git branch or tag to use (e.g., "main", "v1.0.0"). Defaults to repository default branch.
    """
    path: str | None = None
    """
    Path to marketplace.json within repo (defaults to .claude-plugin/marketplace.json)
    """


class MarketplaceSourceGit(ClaudeCodeBaseModel):
    """
    Where to fetch the marketplace from
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["git"] = "git"
    """
    Identifies the marketplace source type
    """
    url: str = Field(..., pattern="\\.git$")
    """
    Full git repository URL
    """
    ref: str | None = None
    """
    Git branch or tag to use (e.g., "main", "v1.0.0"). Defaults to repository default branch.
    """
    path: str | None = None
    """
    Path to marketplace.json within repo (defaults to .claude-plugin/marketplace.json)
    """


class MarketplaceSourceNpm(ClaudeCodeBaseModel):
    """
    Where to fetch the marketplace from
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["npm"] = "npm"
    """
    Identifies the marketplace source type
    """
    package: str
    """
    NPM package containing marketplace.json
    """


class MarketplaceSourceFile(ClaudeCodeBaseModel):
    """
    Where to fetch the marketplace from
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["file"] = "file"
    """
    Identifies the marketplace source type
    """
    path: str
    """
    Local file path to marketplace.json
    """


class MarketplaceSourceDirectory(ClaudeCodeBaseModel):
    """
    Where to fetch the marketplace from
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["directory"] = "directory"
    """
    Identifies the marketplace source type
    """
    path: str
    """
    Local directory containing .claude-plugin/marketplace.json
    """


class ExtraKnownMarketplaces(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: (
        MarketplaceSourceUrl
        | MarketplaceSourceHostPattern
        | MarketplaceSourceGithub
        | MarketplaceSourceGit
        | MarketplaceSourceNpm
        | MarketplaceSourceFile
        | MarketplaceSourceDirectory
    )
    """
    Where to fetch the marketplace from
    """
    install_location: str | None = Field(None, alias="installLocation")
    """
    Local cache path where marketplace manifest is stored (auto-generated if not provided)
    """


class StrictMarketplaceHostPattern(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["hostPattern"] = "hostPattern"
    """
    Identifies the marketplace source type
    """
    host_pattern: str = Field(..., alias="hostPattern")
    """
    Git host pattern to trust for repositories in source specifications
    """


class StrictMarketplaceGithub(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["github"] = "github"
    """
    Identifies the marketplace source type
    """
    repo: str
    """
    GitHub repository in owner/repo format
    """
    ref: str | None = None
    """
    Git branch, tag, or SHA
    """
    path: str | None = None
    """
    Subdirectory path
    """


class StrictMarketplaceGit(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["git"] = "git"
    """
    Identifies the marketplace source type
    """
    url: str
    """
    Full git repository URL
    """
    ref: str | None = None
    """
    Git branch, tag, or SHA
    """
    path: str | None = None
    """
    Subdirectory path
    """


class StrictMarketplaceUrl(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["url"] = "url"
    """
    Identifies the marketplace source type
    """
    url: AnyUrl
    """
    Direct URL to marketplace.json
    """
    headers: dict[str, str] | None = None
    """
    HTTP headers for authenticated access
    """


class StrictMarketplaceNpm(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["npm"] = "npm"
    """
    Identifies the marketplace source type
    """
    package: str
    """
    NPM package name (supports scoped packages)
    """


class StrictMarketplaceFile(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["file"] = "file"
    """
    Identifies the marketplace source type
    """
    path: str
    """
    Absolute path to marketplace.json file
    """


class StrictMarketplaceDirectory(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["directory"] = "directory"
    """
    Identifies the marketplace source type
    """
    path: str
    """
    Absolute path to directory containing .claude-plugin/marketplace.json
    """


class SkippedMarketplace(AdditionalDirectory):
    pass


class SkippedPlugin(AdditionalDirectory):
    pass


class AllowedDomain(AdditionalDirectory):
    pass


class Network(ClaudeCodeBaseModel):
    """
    Configures network isolation settings for the sandboxed bash environment, including domain restrictions, Unix socket access, and custom proxy configuration.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allow_unix_sockets: list[str] | None = Field(None, alias="allowUnixSockets")
    """
    Allow Unix domain sockets for local IPC (SSH agent, Docker, etc.). Provide an array of specific paths. Defaults to blocking if not specified
    """
    allow_local_binding: bool | None = Field(None, alias="allowLocalBinding")
    """
    Allow binding to local network addresses (e.g., localhost ports). Defaults to false if not specified
    """
    http_proxy_port: int | None = Field(None, alias="httpProxyPort", ge=1, le=65535)
    """
    HTTP proxy port to use for network filtering. If not specified, a proxy server will be started automatically
    """
    socks_proxy_port: int | None = Field(None, alias="socksProxyPort", ge=1, le=65535)
    """
    SOCKS proxy port to use for network filtering. If not specified, a proxy server will be started automatically
    """
    allow_all_unix_sockets: bool | None = Field(None, alias="allowAllUnixSockets")
    """
    Allow all Unix domain socket connections. If true, this overrides allowUnixSockets
    """
    allowed_domains: list[AllowedDomain] | None = Field(None, alias="allowedDomains")
    """
    Allowlist of network domains for sandboxed commands. Supports wildcard patterns like *.example.com
    """
    allow_managed_domains_only: bool | None = Field(None, alias="allowManagedDomainsOnly")
    """
    (Managed settings only) Only allowedDomains and WebFetch(domain:...) allow rules from managed settings are respected. User, project, local, and flag settings domains are ignored. Denied domains are still respected from all sources.
    """


class Sandbox(ClaudeCodeBaseModel):
    """
    Sandbox execution configuration. See https://code.claude.com/docs/en/sandboxing
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    network: Network | None = None
    """
    Configures network isolation settings for the sandboxed bash environment, including domain restrictions, Unix socket access, and custom proxy configuration.
    """
    ignore_violations: dict[str, list[str]] | None = Field(None, alias="ignoreViolations")
    """
    Map of command patterns to filesystem paths to ignore violations for. Use "*" to match all commands
    """
    excluded_commands: list[str] | None = Field(None, alias="excludedCommands")
    """
    Commands that should never run in the sandbox (e.g., ["git", "docker"])
    """
    auto_allow_bash_if_sandboxed: bool | None = Field(True, alias="autoAllowBashIfSandboxed")
    """
    Automatically allow bash commands without prompting when they run in the sandbox. Only applies to commands that will run sandboxed.
    """
    enable_weaker_nested_sandbox: bool | None = Field(None, alias="enableWeakerNestedSandbox")
    """
    Enable weaker sandbox mode for unprivileged docker environments where --proc mounting fails. This significantly reduces the strength of the sandbox and should only be used when this risk is acceptable.Default: false (secure).
    """
    allow_unsandboxed_commands: bool | None = Field(None, alias="allowUnsandboxedCommands")
    """
    Allow commands to run outside the sandbox via the dangerouslyDisableSandbox parameter. When false, the dangerouslyDisableSandbox parameter is completely ignored and all commands must run sandboxed. Default: true.
    """
    enabled: bool | None = None
    """
    Enable sandboxed bash
    """


class Verb(AdditionalDirectory):
    pass


class SpinnerVerbs(ClaudeCodeBaseModel):
    """
    Customize the verbs shown in spinner progress messages
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Literal["append", "replace"] | None = None
    """
    How to combine custom verbs with default spinner verbs: 'append' adds custom verbs to the default list, 'replace' uses only custom verbs
    """
    verbs: list[Verb] = Field(..., min_length=1)
    """
    Custom verbs used in spinner progress text
    """


class Tip(AdditionalDirectory):
    pass


class SpinnerTipsOverride(ClaudeCodeBaseModel):
    """
    Customize the tips displayed in the spinner while Claude is working. See https://code.claude.com/docs/en/settings
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    exclude_default: bool | None = Field(False, alias="excludeDefault")
    """
    If true, only show custom tips. If false or absent, custom tips merge with built-in tips
    """
    tips: list[Tip] = Field(..., min_length=1)
    """
    Custom tip strings to display in the spinner
    """


class CompanyAnnouncement(AdditionalDirectory):
    pass


class PluginConfigs(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mcp_servers: dict[str, dict[str, str | float | bool | list[str]]] | None = Field(
        None, alias="mcpServers"
    )
    """
    User configuration values for MCP servers keyed by server name
    """


class BlockedMarketplaceUrl(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["url"] = "url"
    """
    Block marketplace fetched from direct URL
    """
    url: AnyUrl
    """
    Direct URL to marketplace.json file
    """
    headers: dict[str, str] | None = None
    """
    Custom HTTP headers (e.g., for authentication)
    """


class BlockedMarketplaceGithub(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["github"] = "github"
    """
    Block marketplace from GitHub repository
    """
    repo: str
    """
    GitHub repository in owner/repo format
    """
    ref: str | None = None
    """
    Git branch or tag to use
    """
    path: str | None = None
    """
    Path to marketplace.json within repo
    """


class BlockedMarketplaceGit(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["git"] = "git"
    """
    Block marketplace from git repository URL
    """
    url: str = Field(..., pattern=".*\\.git$")
    """
    Full git repository URL
    """
    ref: str | None = None
    """
    Git branch or tag to use
    """
    path: str | None = None
    """
    Path to marketplace.json within repo
    """


class BlockedMarketplaceNpm(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["npm"] = "npm"
    """
    Block marketplace from NPM package
    """
    package: str
    """
    NPM package containing marketplace.json
    """


class BlockedMarketplaceFile(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["file"] = "file"
    """
    Block marketplace from local file
    """
    path: str
    """
    Local file path to marketplace.json
    """


class BlockedMarketplaceDirectory(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["directory"] = "directory"
    """
    Block marketplace from local directory
    """
    path: str
    """
    Local directory containing .claude-plugin/marketplace.json
    """


class BlockedMarketplaceHostPattern(ClaudeCodeBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["hostPattern"] = "hostPattern"
    """
    Block marketplace by host pattern matching
    """
    host_pattern: str = Field(..., alias="hostPattern")
    """
    Regex pattern to match the host/domain extracted from any marketplace source type
    """


class PermissionRule(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ...,
        examples=[
            "Bash",
            "Bash(npm run build)",
            "Bash(git commit *)",
            "Bash(npm run *)",
            "Bash(ls*)",
            "Bash(git * main)",
            "Edit",
            "MultiEdit",
            "Edit(/src/**/*.ts)",
            "Read(./.env)",
            "Read(./secrets/**)",
            "Read(//Users/alice/secrets/**)",
            "Read(~/Documents/*.pdf)",
            "Task(Explore)",
            "WebFetch",
            "WebFetch(domain:example.com)",
            "mcp__puppeteer",
            "mcp__github__search_repositories",
        ],
        pattern="^((Bash|Edit|ExitPlanMode|Glob|Grep|KillShell|LS|LSP|MultiEdit|NotebookEdit|NotebookRead|Read|Skill|Task|TaskCreate|TaskGet|TaskList|TaskOutput|TaskStop|TaskUpdate|TodoWrite|ToolSearch|WebFetch|WebSearch|Write)(\\((?=.*[^)*?])[^)]+\\))?|mcp__.*)$",
    )
    """
    Tool permission rule.
    See https://code.claude.com/docs/en/settings#permission-rule-syntax
    See https://code.claude.com/docs/en/settings#tools-available-to-claude for full list of tools available to Claude.
    """


class HookConfigCommand(ClaudeCodeBaseModel):
    """
    Bash command hook
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["command"] = "command"
    """
    Hook type
    """
    command: str = Field(..., min_length=1)
    """
    Shell command to execute
    """
    timeout: float | None = Field(None, gt=0.0)
    """
    Optional timeout in seconds
    """
    async_: bool | None = Field(None, alias="async")
    """
    Run this hook asynchronously without blocking Claude Code
    """
    status_message: str | None = Field(None, alias="statusMessage")
    """
    Custom spinner message displayed while the hook runs
    """


class HookConfigPrompt(ClaudeCodeBaseModel):
    """
    LLM prompt hook. See https://code.claude.com/docs/en/hooks#prompt-based-hooks
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["prompt"] = "prompt"
    """
    Hook type
    """
    prompt: str = Field(..., min_length=1)
    """
    Prompt to evaluate with LLM. Use $ARGUMENTS placeholder for hook input JSON.
    """
    model: str | None = None
    """
    Model to use for evaluation. Defaults to a fast model
    """
    timeout: float | None = Field(None, gt=0.0)
    """
    Optional timeout in seconds (default: 30)
    """
    status_message: str | None = Field(None, alias="statusMessage")
    """
    Custom spinner message displayed while the hook runs
    """


class HookConfigAgent(ClaudeCodeBaseModel):
    """
    Agent hook with multi-turn tool access for verification. See https://code.claude.com/docs/en/hooks#agent-based-hooks
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["agent"] = "agent"
    """
    Hook type
    """
    prompt: str = Field(..., min_length=1)
    """
    Prompt describing what to verify. Use $ARGUMENTS placeholder for hook input JSON.
    """
    model: str | None = None
    """
    Model to use for evaluation. Defaults to a fast model
    """
    timeout: float | None = Field(None, gt=0.0)
    """
    Optional timeout in seconds (default: 60)
    """
    status_message: str | None = Field(None, alias="statusMessage")
    """
    Custom spinner message displayed while the hook runs
    """


class HookMatcher(ClaudeCodeBaseModel):
    """
    Hook matcher configuration with multiple hooks
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    matcher: str | None = None
    """
    Optional pattern to match event contexts, case-sensitive. Behavior depends on event type. See https://code.claude.com/docs/en/hooks#matcher-patterns for event-specific details and examples
    """
    hooks: list[HookConfigCommand | HookConfigPrompt | HookConfigAgent]
    """
    Array of hooks to execute
    """


class Permissions(ClaudeCodeBaseModel):
    """
    Tool usage permissions configuration.
    See https://code.claude.com/docs/en/permissions and https://code.claude.com/docs/en/settings#permission-settings
    See https://code.claude.com/docs/en/settings#tools-available-to-claude for full list of tools available to Claude.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allow: list[PermissionRule] | None = None
    """
    List of permission rules for allowed operations
    """
    deny: list[PermissionRule] | None = None
    """
    List of permission rules for denied operations
    """
    ask: list[PermissionRule] | None = None
    """
    List of permission rules that should always prompt for confirmation
    """
    default_mode: (
        Literal["acceptEdits", "bypassPermissions", "default", "delegate", "dontAsk", "plan"] | None
    ) = Field(None, alias="defaultMode")
    """
    Default permission mode.
    "default": prompts on first use.
    "acceptEdits": auto-accepts file edits.
    "plan": read-only, no modifications.
    "delegate": coordination-only for agent team leads (agent teams are experimental; enable via CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS).
    "dontAsk": auto-denies unless pre-approved via permissions.
    "bypassPermissions": skips all prompts (use only in isolated environments).
    See https://code.claude.com/docs/en/permissions
    """
    disable_bypass_permissions_mode: Literal["disable"] | None = Field(
        None, alias="disableBypassPermissionsMode"
    )
    """
    Disable the ability to bypass permission prompts
    """
    additional_directories: list[AdditionalDirectory] | None = Field(
        None, alias="additionalDirectories", examples=[["//Users/alice/Documents", "~/projects"]]
    )
    """
    Additional directories to include in the permission scope
    """


class Hooks(ClaudeCodeBaseModel):
    """
    Custom commands to run before/after tool executions. See https://code.claude.com/docs/en/hooks
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    pre_tool_use: list[HookMatcher] | None = Field(None, alias="PreToolUse")
    """
    Hooks that run before tool calls
    """
    post_tool_use: list[HookMatcher] | None = Field(None, alias="PostToolUse")
    """
    Hooks that run after tool completion
    """
    post_tool_use_failure: list[HookMatcher] | None = Field(None, alias="PostToolUseFailure")
    """
    Hooks that run after a tool fails
    """
    permission_request: list[HookMatcher] | None = Field(None, alias="PermissionRequest")
    """
    Hooks that run when a permission dialog appears
    """
    notification: list[HookMatcher] | None = Field(None, alias="Notification")
    """
    Hooks that trigger on notifications
    """
    user_prompt_submit: list[HookMatcher] | None = Field(None, alias="UserPromptSubmit")
    """
    Hooks that run when a user submits a prompt
    """
    stop: list[HookMatcher] | None = Field(None, alias="Stop")
    """
    Hooks that run when agents finish responding. Does not run on user interrupt
    """
    subagent_start: list[HookMatcher] | None = Field(None, alias="SubagentStart")
    """
    Hooks that run when a subagent is spawned
    """
    subagent_stop: list[HookMatcher] | None = Field(None, alias="SubagentStop")
    """
    Hooks that run when subagents finish responding
    """
    pre_compact: list[HookMatcher] | None = Field(None, alias="PreCompact")
    """
    Hooks that run before the context is compacted
    """
    teammate_idle: list[HookMatcher] | None = Field(None, alias="TeammateIdle")
    """
    Hooks that run when an agent team teammate is about to go idle. Exit code 2 sends feedback and keeps the teammate working. Does not support matchers. Agent teams are experimental. See https://code.claude.com/docs/en/hooks#teammateidle
    """
    task_completed: list[HookMatcher] | None = Field(None, alias="TaskCompleted")
    """
    Hooks that run when a task is being marked as completed. Exit code 2 prevents completion and sends feedback. Does not support matchers. See https://code.claude.com/docs/en/hooks#taskcompleted
    """
    setup: list[HookMatcher] | None = Field(None, alias="Setup")
    """
    UNDOCUMENTED. Hooks that run during repository initialization (--init, --init-only) or maintenance (--maintenance)
    """
    config_change: list[HookMatcher] | None = Field(None, alias="ConfigChange")
    """
    Hooks that run when settings, managed settings, or skill files change during a session. Supports matchers: user_settings, project_settings, local_settings, policy_settings, skills. Command handlers only. Exit code 2 blocks the change (except policy_settings which is audit-only). See https://code.claude.com/docs/en/hooks#configchange
    """
    worktree_create: list[HookMatcher] | None = Field(None, alias="WorktreeCreate")
    """
    Hooks that run when a worktree is created via --worktree or isolation: "worktree" in subagents. Command handlers only, no matchers. Hook must print absolute path to created worktree on stdout; non-zero exit fails creation. See https://code.claude.com/docs/en/hooks#worktreecreate
    """
    worktree_remove: list[HookMatcher] | None = Field(None, alias="WorktreeRemove")
    """
    Hooks that run when a worktree is being removed at session exit or when a subagent finishes. Command handlers only, no matchers. Used for cleanup tasks; cannot block removal. See https://code.claude.com/docs/en/hooks#worktreeremove
    """
    session_start: list[HookMatcher] | None = Field(None, alias="SessionStart")
    """
    Hooks that run when a new session starts
    """
    session_end: list[HookMatcher] | None = Field(None, alias="SessionEnd")
    """
    Hooks that run when a session ends
    """


class ClaudeCodeSettings(ClaudeCodeBaseModel):
    """
    Configuration settings for Claude Code. Learn more: https://code.claude.com/docs/en/settings
    """

    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: str | None = Field(None, alias="$schema")
    """
    JSON Schema reference for Claude Code settings
    """
    api_key_helper: str | None = Field(
        None, alias="apiKeyHelper", examples=["/bin/generate_temp_api_key.sh"], min_length=1
    )
    """
    Path to a script that outputs authentication values
    """
    auto_updates_channel: Literal["stable", "latest"] | None = Field(
        "latest", alias="autoUpdatesChannel"
    )
    """
    Release channel to follow for updates. Use "stable" for a version that is typically about one week old and skips versions with major regressions, or "latest" (default) for the most recent release
    """
    aws_credential_export: str | None = Field(
        None, alias="awsCredentialExport", examples=["/bin/generate_aws_grant.sh"], min_length=1
    )
    """
    Path to a script that exports AWS credentials
    """
    aws_auth_refresh: str | None = Field(
        None, alias="awsAuthRefresh", examples=["aws sso login --profile myprofile"], min_length=1
    )
    """
    Path to a script that refreshes AWS authentication
    """
    cleanup_period_days: int | None = Field(
        30, alias="cleanupPeriodDays", examples=[20, 30, 60], ge=0
    )
    """
    Number of days to retain chat transcripts (0 to disable cleanup)
    """
    env: dict[str, str] | None = Field(
        {},
        examples=[
            {
                "ANTHROPIC_MODEL": "claude-opus-4-1",
                "ANTHROPIC_SMALL_FAST_MODEL": "claude-3-5-haiku-latest",
            }
        ],
    )
    """
    Environment variables to set for Claude Code sessions. See https://code.claude.com/docs/en/model-config#environment-variables for notable variables like CLAUDE_CODE_DISABLE_1M_CONTEXT (disables 1M token context window variants)
    """
    attribution: Attribution | None = None
    """
    Customize attribution for git commits and pull requests. See https://code.claude.com/docs/en/settings#attribution-settings
    """
    include_co_authored_by: bool | None = Field(True, alias="includeCoAuthoredBy")
    """
    DEPRECATED. Use 'attribution' instead. Whether to include the co-authored-by Claude byline in git commits and pull requests (default: true)
    """
    plans_directory: str | None = Field(
        "~/.claude/plans", alias="plansDirectory", examples=["./plans"]
    )
    """
    Customize where plan files are stored. Path is relative to project root (default: ~/.claude/plans)
    """
    respect_gitignore: bool | None = Field(True, alias="respectGitignore")
    """
    Control whether the @ file picker respects .gitignore patterns. When true (default), files matching .gitignore patterns are excluded from suggestions
    """
    permissions: Permissions | None = Field(
        None,
        examples=[
            {
                "allow": ["Bash(git add:*)"],
                "ask": ["Bash(gh pr create:*)", "Bash(git commit:*)"],
                "deny": ["Read(*.env)", "Bash(rm:*)", "Bash(curl:*)"],
                "defaultMode": "default",
            }
        ],
    )
    """
    Tool usage permissions configuration.
    See https://code.claude.com/docs/en/permissions and https://code.claude.com/docs/en/settings#permission-settings
    See https://code.claude.com/docs/en/settings#tools-available-to-claude for full list of tools available to Claude.
    """
    language: str | None = Field(None, examples=["japanese", "spanish", "french"])
    """
    Preferred language for Claude's responses
    """
    model: str | None = None
    """
    Override the default model used by Claude Code. See https://code.claude.com/docs/en/model-config
    """
    available_models: list[str] | None = Field(
        None, alias="availableModels", examples=[["sonnet", "haiku"]]
    )
    """
    Restrict which models users can select. When defined at multiple settings levels (user, project, etc.), arrays are merged and deduplicated. See https://code.claude.com/docs/en/model-config#restrict-model-selection
    """
    effort_level: Literal["low", "medium", "high"] | None = Field("high", alias="effortLevel")
    """
    Control Opus 4.6 adaptive reasoning effort. Lower effort is faster and cheaper for straightforward tasks, higher effort provides deeper reasoning. See https://code.claude.com/docs/en/model-config#adjust-effort-level
    """
    fast_mode: bool | None = Field(False, alias="fastMode")
    """
    Enable fast mode for Opus 4.6 (research preview). Fast mode uses the same model with 2.5x faster output at higher per-token cost. Requires extra usage enabled. Alternatively, toggle with /fast command. See https://code.claude.com/docs/en/fast-mode
    """
    enable_all_project_mcp_servers: bool | None = Field(
        None, alias="enableAllProjectMcpServers", examples=[True]
    )
    """
    Whether to automatically approve all MCP servers in the project. See https://code.claude.com/docs/en/mcp
    """
    enabled_mcpjson_servers: list[EnabledMcpjsonServer] | None = Field(
        None, alias="enabledMcpjsonServers", examples=[["memory", "github"]]
    )
    """
    List of approved MCP servers from .mcp.json. See https://code.claude.com/docs/en/mcp
    """
    disabled_mcpjson_servers: list[DisabledMcpjsonServer] | None = Field(
        None, alias="disabledMcpjsonServers", examples=[["filesystem"]]
    )
    """
    List of rejected MCP servers from .mcp.json. See https://code.claude.com/docs/en/mcp
    """
    allowed_mcp_servers: (
        list[
            AllowedMcpServerByServerName
            | AllowedMcpServerByServerCommand
            | AllowedMcpServerByServerUrl
        ]
        | None
    ) = Field(None, alias="allowedMcpServers")
    """
    Enterprise allowlist of MCP servers that can be used. Applies to all scopes including enterprise servers from managed-mcp.json. If undefined, all servers are allowed. If empty array, no servers are allowed. Denylist takes precedence - if a server is on both lists, it is denied. See https://code.claude.com/docs/en/mcp#restriction-options
    """
    denied_mcp_servers: (
        list[
            DeniedMcpServerByServerName
            | DeniedMcpServerByServerCommand
            | DeniedMcpServerByServerUrl
        ]
        | None
    ) = Field(None, alias="deniedMcpServers")
    """
    Enterprise denylist of MCP servers that are explicitly blocked. If a server is on the denylist, it will be blocked across all scopes including enterprise. Denylist takes precedence over allowlist - if a server is on both lists, it is denied. See https://code.claude.com/docs/en/mcp#restriction-options
    """
    hooks: Hooks | None = Field(
        None,
        examples=[
            {
                "PostToolUse": [
                    {
                        "matcher": "Edit|Write",
                        "hooks": [{"type": "command", "command": "prettier --write", "timeout": 5}],
                    }
                ]
            }
        ],
    )
    """
    Custom commands to run before/after tool executions. See https://code.claude.com/docs/en/hooks
    """
    disable_all_hooks: bool | None = Field(None, alias="disableAllHooks")
    """
    Disable all hooks and statusLine execution. When true in managed settings, user and project-level disableAllHooks cannot override it. See https://code.claude.com/docs/en/hooks#disable-or-remove-hooks
    """
    allow_managed_hooks_only: bool | None = Field(None, alias="allowManagedHooksOnly")
    """
    (Managed settings only) Prevent loading of user, project, and plugin hooks. Only allows managed hooks and SDK hooks. See https://code.claude.com/docs/en/settings#hook-configuration
    """
    allow_managed_permission_rules_only: bool | None = Field(
        None, alias="allowManagedPermissionRulesOnly"
    )
    """
    (Managed settings only) Prevent user and project settings from defining allow, ask, or deny permission rules. Only rules in managed settings apply. See https://code.claude.com/docs/en/settings
    """
    status_line: StatusLine | None = Field(
        None,
        alias="statusLine",
        examples=[{"type": "command", "command": "~/.claude/statusline.sh"}],
    )
    """
    Custom status line display configuration. See https://code.claude.com/docs/en/statusline
    """
    file_suggestion: FileSuggestion | None = Field(
        None,
        alias="fileSuggestion",
        examples=[{"type": "command", "command": "~/.claude/file-suggestion.sh"}],
    )
    """
    Configure a custom script for @ file autocomplete. See https://code.claude.com/docs/en/settings#file-suggestion-settings
    """
    enabled_plugins: dict[str, list[str] | bool | Any] | None = Field(None, alias="enabledPlugins")
    """
    Enabled plugins using plugin-id@marketplace-id format. Example: { "formatter@anthropic-tools": true }. See https://code.claude.com/docs/en/plugins
    """
    extra_known_marketplaces: dict[str, ExtraKnownMarketplaces] | None = Field(
        None, alias="extraKnownMarketplaces"
    )
    """
    Additional marketplaces to make available for this repository. Typically used in repository .claude/settings.json to ensure team members have required plugin sources. See https://code.claude.com/docs/en/plugin-marketplaces
    """
    strict_known_marketplaces: (
        list[
            StrictMarketplaceHostPattern
            | StrictMarketplaceGithub
            | StrictMarketplaceGit
            | StrictMarketplaceUrl
            | StrictMarketplaceNpm
            | StrictMarketplaceFile
            | StrictMarketplaceDirectory
        ]
        | None
    ) = Field(
        None,
        alias="strictKnownMarketplaces",
        examples=[
            [
                {"source": "github", "repo": "acme-corp/approved-plugins"},
                {"source": "npm", "package": "@acme-corp/compliance-plugins"},
            ]
        ],
    )
    """
    (Managed settings only) Allowlist of plugin marketplaces users can add. Undefined = no restrictions, empty array = lockdown. Uses exact matching for source specifications. See https://code.claude.com/docs/en/settings#strictknownmarketplaces
    """
    skipped_marketplaces: list[SkippedMarketplace] | None = Field(None, alias="skippedMarketplaces")
    """
    List of marketplace names the user has chosen not to install when prompted
    """
    skipped_plugins: list[SkippedPlugin] | None = Field(None, alias="skippedPlugins")
    """
    List of plugin IDs (plugin@marketplace format) the user has chosen not to install when prompted
    """
    force_login_method: Literal["claudeai", "console"] | None = Field(
        None, alias="forceLoginMethod", examples=["claudeai"]
    )
    """
    Force a specific login method: "claudeai" for Claude Pro/Max, "console" for Console billing
    """
    force_login_org_uuid: str | None = Field(
        None,
        alias="forceLoginOrgUUID",
        examples=["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"],
        min_length=1,
    )
    """
    Organization UUID to use for OAuth login
    """
    otel_headers_helper: str | None = Field(None, alias="otelHeadersHelper", min_length=1)
    """
    Path to a script that outputs OpenTelemetry headers
    """
    output_style: str | None = Field(
        None, alias="outputStyle", examples=["default", "Explanatory", "Learning"], min_length=1
    )
    """
    Controls the output style for assistant responses. See https://code.claude.com/docs/en/output-styles
    """
    skip_web_fetch_preflight: bool | None = Field(None, alias="skipWebFetchPreflight")
    """
    Skip the WebFetch blocklist check for enterprise environments with restrictive security policies
    """
    sandbox: Sandbox | None = None
    """
    Sandbox execution configuration. See https://code.claude.com/docs/en/sandboxing
    """
    spinner_verbs: SpinnerVerbs | None = Field(None, alias="spinnerVerbs")
    """
    Customize the verbs shown in spinner progress messages
    """
    spinner_tips_enabled: bool | None = Field(True, alias="spinnerTipsEnabled")
    """
    Show tips in the spinner while Claude is working. Set to false to disable tips (default: true)
    """
    spinner_tips_override: SpinnerTipsOverride | None = Field(None, alias="spinnerTipsOverride")
    """
    Customize the tips displayed in the spinner while Claude is working. See https://code.claude.com/docs/en/settings
    """
    terminal_progress_bar_enabled: bool | None = Field(True, alias="terminalProgressBarEnabled")
    """
    Enable the terminal progress bar that shows progress in supported terminals like Windows Terminal and iTerm2 (default: true)
    """
    show_turn_duration: bool | None = Field(True, alias="showTurnDuration")
    """
    Show turn duration messages after responses (e.g., "Cooked for 1m 6s"). Set to false to hide these messages (default: true)
    """
    prefers_reduced_motion: bool | None = Field(False, alias="prefersReducedMotion")
    """
    Reduce or disable UI animations (spinners, shimmer, flash effects) for accessibility
    """
    always_thinking_enabled: bool | None = Field(None, alias="alwaysThinkingEnabled")
    """
    Enable extended thinking by default for all sessions. Typically configured via the /config command rather than editing directly. See https://code.claude.com/docs/en/common-workflows#use-extended-thinking-thinking-mode
    """
    company_announcements: list[CompanyAnnouncement] | None = Field(
        None, alias="companyAnnouncements"
    )
    """
    Company announcements to display at startup (one will be randomly selected if multiple are provided)
    """
    teammate_mode: Literal["auto", "in-process", "tmux"] | None = Field(
        "auto", alias="teammateMode"
    )
    """
    How agent team teammates display: "auto" picks split panes in tmux or iTerm2, in-process otherwise. Agent teams are experimental and disabled by default. Enable them by adding CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS to your settings.json or environment. See https://code.claude.com/docs/en/agent-teams
    """
    plugin_configs: dict[str, PluginConfigs] | None = Field(None, alias="pluginConfigs")
    """
    Per-plugin configuration including MCP server user configs, keyed by plugin ID (plugin@marketplace format). See https://code.claude.com/docs/en/plugins
    """
    allow_managed_mcp_servers_only: bool | None = Field(None, alias="allowManagedMcpServersOnly")
    """
    (Managed settings only) Only allowedMcpServers from managed settings are respected. deniedMcpServers still merges from all sources. Users can still add their own MCP servers, but only the admin-defined allowlist applies.
    """
    blocked_marketplaces: (
        list[
            BlockedMarketplaceUrl
            | BlockedMarketplaceGithub
            | BlockedMarketplaceGit
            | BlockedMarketplaceNpm
            | BlockedMarketplaceFile
            | BlockedMarketplaceDirectory
            | BlockedMarketplaceHostPattern
        ]
        | None
    ) = Field(None, alias="blockedMarketplaces")
    """
    (Managed settings only) Blocklist of marketplace sources. These exact sources are blocked from being added as marketplaces. The check happens before downloading, so blocked sources never touch the filesystem.
    """
