"""Claude SDK for Python."""

from __future__ import annotations

from dotenv import load_dotenv

load_dotenv()


from ._errors import (
    APIError,
    AuthenticationError,
    BillingError,
    ClaudeSDKError,
    CLIConnectionError,
    CLIJSONDecodeError,
    CLINotFoundError,
    InvalidRequestError,
    ProcessError,
    RateLimitError,
    ServerError,
)
from ._internal.transport import Transport
from ._version import __version__
from .anthropic_types import ToolResultContentBlock
from .client import ClaudeSDKClient
from .list_sessions import list_sessions
from .models import (
    AccumulatedUsage,
    AgentDefinition,
    AgentHookHandler,
    AgentHooksConfig,
    ContinueLatest,
    AssistantMessage,
    BaseHookInput,
    CanUseTool,
    ClaudeAgentOptions,
    CommandHookHandler,
    OnUserQuestion,
    ContentBlock,
    HookCallback,
    HookContext,
    HookHandler,
    HookInput,
    HookJSONOutput,
    HookMatcher,
    HookMatcherConfig,
    PromptHookHandler,
    ListSessionsOptions,
    McpSdkServerConfig,
    McpServerConfig,
    Message,
    NotificationHookInput,
    NotificationHookSpecificOutput,
    PermissionMode,
    PermissionRequestHookInput,
    PermissionRequestHookSpecificOutput,
    PermissionResult,
    PermissionResultAllow,
    PermissionResultDeny,
    PermissionUpdate,
    PostToolUseFailureHookInput,
    PostToolUseFailureHookSpecificOutput,
    PostToolUseHookInput,
    PreCompactHookInput,
    PreToolUseHookInput,
    BaseResultMessage,
    ResultErrorMessage,
    ResultMessage,
    ResultSuccessMessage,
    SandboxIgnoreViolations,
    SandboxNetworkConfig,
    SandboxSettings,
    SdkBeta,
    SdkPluginConfig,
    SettingSource,
    StopHookInput,
    SubagentStartHookInput,
    SubagentStartHookSpecificOutput,
    SubagentStopHookInput,
    BaseSystemMessage,
    InitSystemMessage,
    TextBlock,
    ThinkingBlock,
    ThinkingConfig,
    ThinkingConfigAdaptive,
    ThinkingConfigDisabled,
    ThinkingConfigEnabled,
    ToolPermissionContext,
    ToolResultBlock,
    ToolUseBlock,
    UserMessage,
    UserDocumentPrompt,
    UserDocumentURLPrompt,
    UserImagePrompt,
    UserImageURLPrompt,
    UserPlainTextDocumentPrompt,
    UserPrompt,
    UserPromptSubmitHookInput,
    UserTextPrompt,
    FromPR,
    NewSession,
    ResumeSession,
    SDKSessionInfo,
    SessionConfig,
    DocumentMediaType,
    ImageMediaType,
    PlainTextMediaType,
)
from .query import query
from .mcp_utils import SdkMcpTool, tool, create_sdk_mcp_server
from .session import (
    ConversationTurn,
    Session,
    SessionManager,
    SessionSnapshot,
    SessionState,
    ToolCallSummary,
)

# MCP Server Support

__cli_version__ = "2.1.11"


__all__ = [
    # API Errors
    "APIError",
    "AccumulatedUsage",
    # Agent support
    "AgentDefinition",
    # Hook support
    "AgentHookHandler",
    "AgentHooksConfig",
    "AssistantMessage",
    "AuthenticationError",
    "BaseHookInput",
    "BaseResultMessage",
    "BaseSystemMessage",
    "BillingError",
    "CLIConnectionError",
    "CLIJSONDecodeError",
    "CLINotFoundError",
    # Tool callbacks
    "CanUseTool",
    "ClaudeAgentOptions",
    "ClaudeSDKClient",
    # Errors
    "ClaudeSDKError",
    "CommandHookHandler",
    "ContentBlock",
    # Session config
    "ContinueLatest",
    "ConversationTurn",
    "DocumentMediaType",
    "FromPR",
    "HookCallback",
    "HookContext",
    "HookHandler",
    "HookInput",
    "HookJSONOutput",
    "HookMatcher",
    "HookMatcherConfig",
    "ImageMediaType",
    "InitSystemMessage",
    "InvalidRequestError",
    "ListSessionsOptions",
    "McpSdkServerConfig",
    "McpServerConfig",
    "Message",
    "NewSession",
    "NotificationHookInput",
    "NotificationHookSpecificOutput",
    "OnUserQuestion",
    # Types
    "PermissionMode",
    "PermissionRequestHookInput",
    "PermissionRequestHookSpecificOutput",
    "PermissionResult",
    "PermissionResultAllow",
    "PermissionResultDeny",
    "PermissionUpdate",
    "PlainTextMediaType",
    "PostToolUseFailureHookInput",
    "PostToolUseFailureHookSpecificOutput",
    "PostToolUseHookInput",
    "PreCompactHookInput",
    "PreToolUseHookInput",
    "ProcessError",
    "PromptHookHandler",
    "RateLimitError",
    "ResultErrorMessage",
    "ResultMessage",
    "ResultSuccessMessage",
    "ResumeSession",
    "SDKSessionInfo",
    "SandboxIgnoreViolations",
    "SandboxNetworkConfig",
    # Sandbox support
    "SandboxSettings",
    # Beta support
    "SdkBeta",
    "SdkMcpTool",
    # Plugin support
    "SdkPluginConfig",
    "ServerError",
    "Session",
    "SessionConfig",
    # Session management
    "SessionManager",
    "SessionSnapshot",
    "SessionState",
    "SettingSource",
    "StopHookInput",
    "SubagentStartHookInput",
    "SubagentStartHookSpecificOutput",
    "SubagentStopHookInput",
    "TextBlock",
    "ThinkingBlock",
    # Thinking configuration
    "ThinkingConfig",
    "ThinkingConfigAdaptive",
    "ThinkingConfigDisabled",
    "ThinkingConfigEnabled",
    "ToolCallSummary",
    "ToolPermissionContext",
    "ToolResultBlock",
    "ToolResultContentBlock",
    "ToolUseBlock",
    # Transport
    "Transport",
    "UserDocumentPrompt",
    "UserDocumentURLPrompt",
    "UserImagePrompt",
    "UserImageURLPrompt",
    "UserMessage",
    "UserPlainTextDocumentPrompt",
    "UserPrompt",
    "UserPromptSubmitHookInput",
    "UserTextPrompt",
    "__version__",
    # MCP Server Support
    "create_sdk_mcp_server",
    "list_sessions",
    # Main exports
    "query",
    "tool",
]
